# -*- coding: utf-8 -*-
"""Assignment of Data Mining BY abbas AHMAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geUS8LI1HNnNOdT7RZPEaWBdwYSp2yNw

**I AM ABBAS AHMAD, STUDENT OF COMPUTER SCIENSE 5TH SEMESTER.**

**THIS IS THE ASSIGNMENT OF LECTURER AHMAD ULLAH SIR, OF DATA MINING SUBECT.**

**THIS ASSIGNMENT IS ABOUT MACHINE LEARNING & DATA SCIENCE SURVEY OF 2017.**


**THAT'S IT!**
"""

!pip install pandas

import pandas as pd

df = pd.read_csv("/content/multipleChoiceResponses.csv", encoding="latin-1")

df.head( )

df.tail(6)

df.shape

df.dtypes

df['Age'].describe()

df.describe()

df['Country'].describe()

df.iloc[5000]

df.loc[df["Country"] == "Pakistan"]

df.sort_values(by = "Age").head()

df.sort_values(by = "Age", ascending=False).head()

"""**Dropping** **Columns**"""

df = df.drop(['JobFactorLeaderReputation'], axis=1)

"""**Dropping** **rows**"""

df.shape

# Count the number of duplicate rows
duplicate_rows = df[df.duplicated()]
num_duplicate_rows = duplicate_rows.shape[0]

# Print the number of duplicate rows
print(f"Number of duplicate rows: {num_duplicate_rows}")

# Print the shape of the dataframe
print(f"Shape of dataframe: {df.shape}")

df.count() #count the number of rows

df = df.drop_duplicates()
df.head(5)

df.count()

"""**Dropping the missing or null values**"""

print(df.isnull().sum())

df.loc[df["Country"] == "Israel"]

"""**Remove Israel**"""

# Create a list of countries to be removed
countries_to_remove = ['Israel']

# Drop rows where the "Country" column value is in the list of countries to remove
df = df[~df['Country'].isin(countries_to_remove)]

"""***THE*** ***END*** ***OF*** ***PROJECT***"""