# -*- coding: utf-8 -*-
"""Assignment 01 Abbas Ahmad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAPecyjQLhqPgaesVYkJ_onJ-ugOf5cd
"""

Introduction="""My Name is Abbas Ahmad From KPK (Swabi).
                I am a student of BS Computer Science.
                May ALLAH Success you and your team in Akhira and also in Dunya
                Thank you so much Sir Muhammad Irfan Malik and DR Sheraz Saib and other team members"""

# Creating a list named "fruits" containing three different fruits
fruits = ["Apple", "Banana", "Orange"]

# Displaying the items using a for loop
for fruit in fruits:
    print(fruit)

# Creating a tuple named "numbers" with five random numbers
numbers = (1, 4, 7, 2, 5)

# Displaying the items using a for loop
for number in numbers:
    print(number)

# Creating a set named "colors" with three different colors
colors = {"White", "Green", "Red"}

# Displaying the items using a for loop
for color in colors:
    print(color)

# Creating a dictionary named "student" with key-value pairs
student = {"name": "Abbas Ahmad",
    "age": 21,
    "grade": "A"
}

# Iterating over the dictionary using a for loop and displaying its keys
print("Keys:")
for key in student.keys():
    print(key)

# Iterating over the dictionary using a for loop and displaying its values
print("\nValues:")
for value in student.values():
    print(value)

#Create a multi-line string named "poem" with a short poem about Python
poem = """
In the world of code, a serpent glides,
Pythonic magic, where logic resides.
Indentation rules, a syntax so clean,
A language powerful, a developer's dream.

From scripts to apps, it slithers with grace,
Guido's creation, in every codebase.
Dynamic and versatile, with libraries vast,
Pythonic poetry, a language built to last.

In the realm of algorithms, it swiftly prevails,
A syntax symphony, where logic trails.
With modules and functions, it dances and weaves,
In the heart of developers, Python achieves.
"""

#An if statement to check if the length of the "fruits" list is greater than 3. If it is, print "You have many fruits!"
fruits = ["Apple", "Banana", "Orange", "Grapes"]

if len(fruits) > 3:
    print("You have many fruits!")

# Taking numerical grade as input from the user
numerical_grade = float(input("Enter the numerical grade: "))

# Classifying the grade into categories
if numerical_grade >= 90:
    letter_grade = "A"
elif 80 <= numerical_grade <= 89:
    letter_grade = "B"
elif 70 <= numerical_grade <= 79:
    letter_grade = "C"
elif 60 <= numerical_grade <= 69:
    letter_grade = "D"
else:
    letter_grade = "F"

# Displaying the corresponding letter grade
print(f"The corresponding letter grade is: {letter_grade}")

# Taking temperature in Celsius as input from the user
temperature_celsius = float(input("Enter the temperature in Celsius: "))

# Classifying the temperature into categories
if temperature_celsius < -10:
    category = "Freezing"
elif -10 <= temperature_celsius < 0:
    category = "Cold"
elif 0 <= temperature_celsius < 20:
    category = "Moderate"
elif 20 <= temperature_celsius < 30:
    category = "Warm"
else:
    category = "Hot"

# Displaying the category for the given temperature
print(f"The temperature is classified as: {category}")