print("Assalamualaikum")
print("Welcome to the football team name generator.")
city=input("Which city did you grow up in? \n")
pet=input("What is the name of a pet? \n")
print("Your team name could be " +city+ " " + pet )